services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: EcoCode
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11062002Andrey
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  java-app:
    build:
      context: ./java-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/EcoCode
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 11062002Andrey
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

  telegram-bot:
    build:
      context: ./telegram-bot
    environment:
      JAVA_API_URL: http://java-app:8080/api/users
    depends_on:
      - java-app
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # Доступ к pgAdmin через http://localhost:5050
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge